### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot destructure property 'href' of 'n' as it is undefined.

### ISSUE THREAD

**Issue by Sicmatr1x** [wvit/web-document#2]
![image](https://github.com/wvit/web-document/assets/26240752/4aa0dfcd-f29f-49da-8c4b-7390c7df0ade)
![image](https://github.com/wvit/web-document/assets/26240752/1a1be6f1-fe78-466a-bcdb-4e7f2c03fdcb)

```
index.js:1  Uncaught (in promise) TypeError: Cannot destructure property 'href' of 'n' as it is undefined.
    at l (index.js:1:213)
    at async index.js:1:521
```

**Comment by wvit** [comment]
Hello, thank you for your issue. This problem arises because you did not refresh your webpage after installing the plugin. Please refresh the webpage you want to save, and it should work fine.

The error shown in the screenshot has been addressed with compatibility fixes. Please check the latest version v1.1.1 (https://github.com/wvit/web-document/releases/tag/v1.1.1), and remember to refresh the webpage after installation.

By the way, I noticed that you are using the Edge browser. Although it uses the Chromium engine like Chrome, I just tested it and found that its connection to indexedDB seems to be slower than Chrome's. If there are more users in the future, I will consider optimizing specifically for Edge. Additionally, I am in the process of publishing this extension to both the Chrome and Edge extension markets. Thank you for using it.
